packages:
  - packages/*

overrides:
  unconfig: "7.3.2"
  sass: "^1.98.0"
  "@intlify/core-base": "11.3.0"
  "@intlify/shared": "11.3.0"
  entities: "^7.0.1"

onlyBuiltDependencies:
  - "@carbon/icons"
  - "@parcel/watcher"
  - core-js
  - core-js-pure
  - ejs
  - es5-ext
  - esbuild
  - sharp
  - simple-git-hooks
  - vue-demi
  - yorkie
