/**
 * 组件库清单：组件名与类型导出名的唯一数据源。
 * 新增/删除组件时只需修改此文件，resolver 与运行时导出由此派生，避免硬编码不同步。
 */
export const VUE_ELEMENT_CUI_COMPONENT_NAMES = [
	"CuiTable",
	"CuiForm",
	"CuiSearch",
	"CuiDialog",
	"CuiDialogForm",
	"CuiDetail",
	"CuiTab",
	"CuiExcel",
	"CuiSelectBox",
	"CuiSelect",
	"CuiSelectEnum",
	"CuiSelectDict",
	"CuiRadioEnum",
	"CuiRadioDict",
	"CuiCheckboxEnum",
	"CuiAutocomplete",
] as const;

export const VUE_ELEMENT_CUI_TYPE_EXPORT_NAMES = [
	"CuiTableProps",
	"CuiTableColumn",
	"SortChangeEvent",
	"SelectionChangeEvent",
	"CuiFormProps",
	"CuiFormField",
	"CuiFormFieldType",
	"CuiFormSelectOption",
	"CuiFormValidateResult",
	"CuiSearchProps",
	"CuiSearchField",
	"CuiDialogProps",
	"CuiDialogEmits",
	"CuiDialogFormProps",
	"CuiDialogFormEmits",
	"CuiDetailProps",
	"CuiDetailField",
	"CuiTabProps",
	"CuiTabItem",
	"CuiExcelProps",
	"CuiExcelEmits",
	"CuiSelectBoxProps",
	"CuiSelectBoxEmits",
	"CuiSelectBoxOption",
	"CuiSelectProps",
	"CuiSelectEmits",
	"CuiSelectOption",
	"CuiSelectEnumProps",
	"CuiSelectEnumEmits",
	"CuiSelectEnumOption",
	"CuiSelectDictProps",
	"CuiSelectDictEmits",
	"CuiSelectDictOption",
	"CuiRadioEnumProps",
	"CuiRadioEnumEmits",
	"CuiRadioEnumOption",
	"CuiRadioDictProps",
	"CuiRadioDictEmits",
	"CuiRadioDictOption",
	"CuiCheckboxEnumProps",
	"CuiCheckboxEnumEmits",
	"CuiCheckboxEnumOption",
	"CuiAutocompleteProps",
	"CuiAutocompleteEmits",
	"CuiAutocompleteSuggestion",
] as const;
